16c16
< 	   demand.c utils.c tty.c eap.c chap-md5.c session.c
---
> 	   demand.c utils.c tty.c eap.c chap-md5.c session.c syncppp.c
20c20
< 	upap.h eap.h
---
> 	upap.h eap.h syncppp.h 
25c25
< 	   eap.o chap-md5.o session.o
---
> 	   eap.o chap-md5.o session.o syncppp.o
36c36
< LIBS =
---
> LIBS = -lpthread
